### ISSUE TITLE
Execution service

### ISSUE THREAD

**Issue by proman3419** [k8loud/themis-executor#6]
**DoD**
There is a core service for executing predefined actions.

**Comment by pgorgolew** [comment]
this should be task for ExecutorController not service (afaik)

**Comment by proman3419** [comment]
> this should be task for ExecutorController not service (afaik)

Not really but the controller can be a part of this feature.
Check [this PR](https://github.com/k8loud/themis-executor/pull/3), the controller is the blue component and the service is another component which purpose is defined in DoD of this story.
