### ISSUE TITLE
Add possibility to delete instances with specific server ids

### ISSUE THREAD

**Issue by proman3419** [k8loud/themis-executor#63]
There should be a possibility to add/remove instances relativly to the current count.
Flags should be used to achieve this:
- `UP` - add `x` instances
- `DOWN` - remove `x` instances
- `EXACT` - after applying the request there should be `x` instances

**Comment by pgorgolew** [comment]
- `Up` we have addInstanceAction
- `Down` - currently our action deletes all instances that match name pattern
- `Exact` -> think we don't need it if we change `Down` to delete `X` instances

**Comment by proman3419** [comment]
`Exact` is not required for our use case, can be removed from the scope

**Comment by pgorgolew** [comment]
As disscussed:
1. DeleteInstances with optional parameters for deleting servers with specific ids (pattern: `id1,id2,...,idN`)
2. create a method in openstackService to list all servers with specific name pattern
